# Site settings
#baseurl: '/deep-fried-jekyll-theme'
url: 'https://lyehengfoo.tk'
#title: 'Deep-fried'
#description: 'A minimalist Jekyll theme optimized for readability and performance.'
#author: 'Steven McLintock'
title: 'DIY Hideout'
description: 'A unique hideout place for all DIY goers.'
author: 'Lye Heng Foo'

# Build settings
permalink: /:year/:month/:day/:title/
plugins: [ jekyll-sitemap, jekyll-feed, jekyll-seo-tag ]
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
sass:
  style: compressed

# Stylesheets
stylesheets:
  - '/css/stylesheet.css'
  - '/css/syntax.css'

# Google Analytics
google-analytics:
  enabled: false
  id: 'G-DKESF4DMDC'

# The primary language used by the website
language: 'en'

# Favicon and icons for iOS, Android
# These should ideally be located in the root directory
apple-touch-icon: '/apple-touch-icon.png'
favicon-32: '/favicon-32x32.png'
favicon-16: '/favicon-16x16.png'
site-manifest: '/site.webmanifest'

# The logo motif
logo-motif:
  enabled: true
  #src: '/assets/img/deep-fried-chocolate-motif.png'
  src: '/assets/img/DIYHideout-270x270.png'
  width: '135'
  height: '135'

# The logo title
logo-title:
  enabled: true

# Header menu
header-menu:
- { name: 'Home', url: '/' }
- { name: 'About Me', url: '/about' }
- { name: 'My Articles', url: '/articles' }
- { name: 'My Resume', url: '/resume.html' }

# Footer menu
footer-menu:
- { name: 'Home', url: '/' }
- { name: 'About Me', url: '/about' }
- { name: 'My Articles', url: '/articles' }
- { name: 'RSS', url: '/feed.xml' }

# Homepage
homepage:
  header-text: 'Welcome to DIY Hideout'
  intro-text: 'DIY Hideout  is the personal website of Lye Heng Foo.
               Lye Heng is a Malaysian freelance primarily working on web design & software app development.
               He is familiar with many open-source applications and software technologies, and
               he loves to tinker with several software technologies.
               On his freetime, he is a hobbyist working on many DIY projects and repairing broken stuff.
               He loves building automation projects using Arduino and ESP8266 micro-controllers.
               And he also loves to share about IT and computing latest technologies with his friends.'
  intro-image: 'diy-workbench-crop-small.jpg'
  latest-articles-enabled: true
  latest-articles-title-text: 'Latest Articles'
  latest-articles-link-enabled: true
  latest-articles-link-url: '/articles'
  latest-articles-link-text: 'View all articles'

# Articles
articles:
  header-text: 'All Articles'
  excerpt-enabled: true
  read-more-enabled: true
  read-more-text: 'Read more'

# Post Icons
icons:
  enabled: true

# Related posts (only works if you use tags)
related-posts:
  enabled: true
  header-text: 'More articles like this ...'
  limit: 3
  no-related-articles-text: 'No similar articles found.'

# Written on (post info displayed underneath the H1)
written-on:
  enabled: true
  by-text: 'By'
  on-text: 'on'
